---
- hosts: localhost

  vars:
    http_port: 80

  user: ubuntu
  sudo: true


  tasks:
  - name: install nginx
    yum: name=nginx state=present

  - name: ensure nginx is running
    service: name=nginx state=running

  - name: wait for nginx to be running
    wait_for: port={{ http_port  }} delay=3
